const LIBRARY_PATH_LOAD_REQUEST = 'LIBRARY_PATH_LOAD_REQUEST';
const LIBRARY_PATH_LOADED = 'LIBRARY_PATH_LOADED';

const LIBRARY_SCANNER_START = 'LIBRARY_SCANNER_START';
const LIBRARY_SCANNER_FINISHED = 'LIBRARY_SCANNER_FINISHED';

const VIEW_CHANGE = 'VIEW_CHANGE';

const CURRENT_FILE_SELECT = 'CURRENT_FILE_SELECT';

export {
  LIBRARY_PATH_LOAD_REQUEST,
  LIBRARY_PATH_LOADED,
  LIBRARY_SCANNER_START,
  LIBRARY_SCANNER_FINISHED,
  VIEW_CHANGE,
  CURRENT_FILE_SELECT,
};
